# Generated by Django 5.2.4 on 2025-11-22 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_default_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7–15 digits, spaces or dashes allowed).', regex='^\\+?[\\d\\s\\-]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid postcode (3–10 letters/numbers).', regex='^[A-Za-z0-9\\s\\-]{3,10}$')]),
        ),
    ]
